<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script data-cfasync="false" type="text/javascript">
    userActionEvents = ['scroll', 'mousemove', 'touchstart'];
    removeEvent = true;
    window.immediateLoad = false;
    window.initEvents = function (events, functionName, removed) {
        if (window.immediateLoad && !removed) {
            functionName.apply(null);
        } else if (!window.immediateLoad) {
            events.forEach(function (event) {
                if (!removed) {
                    window.addEventListener(event, functionName, {passive: true});
                } else {
                    window.removeEventListener(event, functionName);
                }
            });
        }
    };
    const elementIEvent = new Event('element-intersection');
    !(function (w) {
        if ("IntersectionObserver" in w) {
            w.elementIntersectionObserver = new IntersectionObserver(function (entries, observer) {
                entries.forEach(function (entry) {
                    if (entry.isIntersecting) {
                        var _element = entry.target;
                        w.elementIntersectionObserver.unobserve(_element);
                        // Dispatch the event.
                        _element.dispatchEvent(elementIEvent);
                    }
                });
            }, {rootMargin: '100px', threshold: 0});
        }
    })(window);
    window.IntersectionElement = function (_element) {
        window.elementIntersectionObserver.observe(_element);
    }
    !(function (w, d) {
        if ("IntersectionObserver" in w) {
            w.lazyloadImageAllPage = new IntersectionObserver(function (entries, observer) {
                entries.forEach(function (entry) {
                    if (entry.isIntersecting) {
                        var image = entry.target;
                        image.src = image.dataset.src;
                        image.onload = null;
                        w.lazyloadImageAllPage.unobserve(image);
                    }
                });
            }, d);
        }
    })(window, {rootMargin: '100px', threshold: 0});
    window.CWVLazyLoad = function (options, _element) {
        _element.onload = null;
        (function (element) {
            window.lazyloadImageAllPage.observe(element);
        })(_element);
    }
</script>
