<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var Hidro\CoreWebVitals\Helper\Data $helper */
$helper = $this->helper(\Hidro\CoreWebVitals\Helper\Data::class);
?>
<script data-cfasync="false" type="text/javascript">
    var userActionEvents = ['scroll', 'mousemove', 'touchstart'];
    window.deferRecaptcha = <?= json_decode($helper->isDeferRecaptcha());?>;

    removeEvent = true; window.immediateLoad = false;
    window.initEvents = function (events, functionName, removed) {
        if (window.immediateLoad && !removed) {
            functionName.apply(null);
        } else if (!window.immediateLoad) {
            events.forEach(function (event) {
                if (!removed) {
                    window.addEventListener(event, functionName, {passive: true});
                } else {
                    window.removeEventListener(event, functionName);
                }
            });
        }
    };
    const elementIEvent = new Event('element-intersection');
    !(function (w) {
        if ("IntersectionObserver" in w) {
            w.elementIntersectionObserver = new IntersectionObserver(function (entries, observer) {
                entries.forEach(function (entry) {
                    if (entry.isIntersecting) {
                        var _element = entry.target;
                        w.elementIntersectionObserver.unobserve(_element);
                        // Dispatch the event.
                        _element.dispatchEvent(elementIEvent);
                    }
                });
            }, {rootMargin: '50px', threshold: 0});
        }
    })(window);
    window.IntersectionElement = function (_element, callBack) {
        _element.addEventListener('element-intersection', callBack, {passive: false});
        window.elementIntersectionObserver.observe(_element);
    }
    window.CWVLazyLoad = function (options, _element) {
        _element.onload = null;
        IntersectionElement(_element, function () {
            this.src = this.dataset.src;
        });
    }
</script>
